autoprotocol/autoprotocol-python

- autoprotocol/protocol.py
Omitting both the discard and storage arguments should raise a ValueError as the docs say. The code is in place, but was never reached due to this assert statement. This would also give a meaningless assertion error instead of the nice error message.
> Remove redundant assert

- autoprotocol/harness.py
Permits the following in the manifest:
```json
{
"inputs": {
"parameter_name": {
"type": "volume",
"default": "3:microliter"
}
}
}
```
> Support more complex input descriptions

- docs/README.rst
- docs/index.rst
Note that I didn't update the files in `docs/_build/`, as AFAIK the online docs get rebuilt from the source.
> Fix docs typo: methdods -> methods

- autoprotocol/container.py
- autoprotocol/harness.py
- autoprotocol/instruction.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
* Removed use of `.iteritems()` and `.itervalues()`, iterate over dictionary's keys and manually grab the values
* Fall back on `str` type from `basestring`
* Define `xrange = range` when running python3
* Define `__eq__` and `__lt__` for python3 comparisons
The unit tests pass when running Python 3.4.2 as well as Python 2.7.5. I found a few places in the code where python2 conventions were still used, but the tests still passing. I fixed them, but there may yet be other functions where using python3 would throw an error.
> python3 support

- autoprotocol/harness.py
Adds the `warm_30` temperature.  This is an oddball temperature that should only be used by those who know they can use it.
> harness: add custom temperature for internal use

- autoprotocol/unit.py
- test/unit_test.py
This PR adds support to perform ```int * Unit``` previously only ```Unit * int``` was supported. In reference to #72
> Support int * Unit

- autoprotocol/pipette_tools.py
This would crash without sys imported.
I mean, the crash only happens on the call to sys.exit, so that’s not so bad, but y'know.
Context: https://transcriptic.slack.com/archives/D0BEF5DD2/p1444075059000008
> Fixed a (really minor) potential crash bug

- CHANGELOG.md
- autoprotocol/instruction.py
- autoprotocol/protocol.py
- autoprotocol/util.py
- test/protocol_test.py
absorbance, luminescence, fluorescence with incubate_before and temperature
Summary:
Extend functionality of spectrophotometry instructions (absorbance, luminescence, fluorescence)
Included a function to create incubation dictionaries
This update implements changes propsed by the "Add incubate_before and temperature to spectrophotometry instructions" ASC
https://docs.google.com/document/d/1xlTz4bEd4_fOjCu6MmFrrKA-IqTRgLKuJxu3EScud9c/edit
Test Plan: passes tox
> Add extensions to Spetrophotometry instructions 

- autoprotocol/protocol.py
Argument is case-sensitive and should be down-cased in description for consistency. Also, added ellipsis to autoprotocol output to show that example python would generate at least one more instruction for clarity.
> Make casing of concentration arg more obvious

- autoprotocol/protocol.py
- test/protocol_test.py
Acoustic transfer now ensures that the volume pipetted is droplet_size compatible and on one_source only generates droplet_size compatible transfers.
mix now takes a one_tip true parameter
> Changes to acoustic transfer and mix

- CHANGELOG.md
- autoprotocol/protocol.py
Summary: convert all pipette volumes to microliters prior to downstream math
Fixes Issue #127 
Test Plan: tox
Reviewers: yangchoo
Differential Revision: https://work.r23s.net/D5439
> convert pipette operations to ul before processing

- CHANGELOG.md
- autoprotocol/protocol.py
- docs/setup.py
- setup.py
- test/protocol_test.py
Allow `distribute_speed` and properly assign `distribute_target` in the Distribute Instruction.
> Distribute Instruction Fix

- autoprotocol/util.py
- docs/changelog.rst
- docs/setup.py
- setup.py
- test/protocol_test.py
Additional validation on optional `incubate_before` parameters in Absorbance, Luminescence and Fluorescence Instructions.
> Update valid incubate_before params

- .arclint
- .pylintrc
- autoprotocol/__init__.py
- autoprotocol/harness.py
- autoprotocol/instruction.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- test/protocol_test.py
- tox.ini
Pylint allows for much more powerful and configurable linting compared to flake8. In particular this will be really helpful in standardizing docstrings.
> Change default linting engine to pylint

- autoprotocol/instruction.py
- docs/changelog.rst
- test/instruction_test.py
Summary:
empty list/dicts should not end up in the final autoprotol json. a single call to _remove_empty_fields does will return an empty dict for cases in which a dict is given with values that are all None, and will return an empty list for cases in which a list is passed with all None elements.
ex:
```
foo = {"not_empty": 1, "empty": {"a": None, "b": None, "c": None}}
Instruction._remove_empty_fields(foo)
>>> {'not_empty': 1, 'empty': {}}
Instruction._remove_empty_fields(Instruction._remove_empty_fields(foo))
>>> {'not_empty': 1}
foo = {"not_empty": 1, "empty": [None, None, None]}
Instruction._remove_empty_fields(foo)
>>> {'not_empty': 1, 'empty': []}
Instruction._remove_empty_fields(Instruction._remove_empty_fields(foo))
>>> {'not_empty': 1}
```
Test Plan: pytest
Reviewers: yangchoo, …
> avoid returning empty dict/list

- autoprotocol/container_type.py
- docs/changelog.rst
Add the `384-flat-white-clear` ContainerType as part of the deprecation path for `384Flat` as the Corning 3706 is no longer being produced.
> Add 384-flat-white-clear container type

- autoprotocol/instruction.py
- autoprotocol/protocol.py
- docs/changelog.rst
- test/protocol_test.py
The `op` field has been removed from `Instruction.data`. The correct way to get an `Instruction`'s full specification is now to reference its `__dict__`.
> Fix instruction serialization

- autoprotocol/liquid_handle/liquid_handle_method.py
- autoprotocol/liquid_handle/transfer.py
- docs/changelog.rst
Update Transfer LiquidHandleMethod defaults to use more sensible z positions; unbreak PreMixBlowoutTransfer.
> Refactor LiHa defaults

- autoprotocol/protocol.py
- docs/changelog.rst
Transfer `tip_type` assignment was breaking on cases where there were the volume is large enough to necessitate splitting.
> Fix transfer tip_type assignment

- autoprotocol/builders.py
- autoprotocol/container_type.py
- autoprotocol/liquid_handle/liquid_class.py
- autoprotocol/liquid_handle/tip_type.py
- autoprotocol/unit.py
- setup.py
- tox.ini
- Make CI dependencies more readable
- Update tox to use specific python versions for docs and linting instead of default system python
- Fix lint warnings introduced by a pylint update
> Update CI and unbreak existing lint warnings

- autoprotocol/builders.py
- docs/changelog.rst
- test/builder_test.py
Thermocycle dyes builder was using wells instead of ints which was not to Autoprotocol spec.
> Fix Thermocycle.dyes using Well instead of Int

- autoprotocol/container.py
- autoprotocol/container_type.py
- autoprotocol/protocol.py
- autoprotocol/util.py
- docs/changelog.rst
- test/conftest.py
- test/container_test.py
- test/liquid_handle_integration_test.py
- test/protocol_test.py
- test/util_test.py
Add a flag to `Protocol` to propagate aliquot properties when liquid handling.
Add new methods to `Container` and `ContainerType` for fetching WellGroups.
> Add flag to propagate aliquot props with liha

- autoprotocol/container.py
- docs/changelog.rst
- test/container_test.py
- test/well_test.py
Make `Well.add_properties` extend the original instead of replacing it if both values are lists.
> Make Well.add_properties extend lists

- autoprotocol/protocol.py
- docs/changelog.rst
- test/protocol_test.py
This diff adds initial cover states of refs to the output of `Protocol.as_dict`.
> Add cover state to ref opts

- autoprotocol/container.py
- docs/changelog.rst
- test/container_test.py
We added support for non-str values in properties as part of PR190.  We did not update `wells_with` and this adds in the missing support.
> Fix for wells_with to add support for non-str values

- docs/changelog.rst
Sphinx isn't happy with spaces between the changelog tag and PR number. This fixes those.
> Fix changelog formatting

- .travis.yml
- autoprotocol/__init__.py
- autoprotocol/builders.py
- autoprotocol/container.py
- autoprotocol/container_type.py
- autoprotocol/harness.py
- autoprotocol/instruction.py
- autoprotocol/liquid_handle/__init__.py
- autoprotocol/liquid_handle/liquid_class.py
- autoprotocol/liquid_handle/liquid_handle_method.py
- autoprotocol/liquid_handle/mix.py
- autoprotocol/liquid_handle/tip_type.py
- autoprotocol/liquid_handle/transfer.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
- autoprotocol/util.py
- docs/changelog.rst
- docs/index.rst
- setup.py
- test/protocol_test.py
- tox.ini
With Python 2.7 EOL coming at 1 Jan, 2020, we need to upgrade to Python 3.
As part of this breaking diff, we've also decided to only support Python 3.5 upwards, change the underlying test infrastructure, update and pin some dependencies as well as keeping the documentation up-to-date.
> Upgrade ApPy to Python 3

- autoprotocol/version.py
- docs/changelog.rst
- setup.cfg
Bumping version to 6.0.0 for release. Major version bump since Py3 upgrade breaks previous compatibility. 
Also removing universal flag from wheels, since this is only Python 3 compatible now
> Bump version to 6.0.0 for release

- autoprotocol/protocol.py
- docs/changelog.rst
- setup.py
Correcting default `bath` frequency for Sonicate method.
- Change from 20kHz --> 40kHz
> Correct bath frequency to 40kHz

- autoprotocol/harness.py
- autoprotocol/version.py
- docs/changelog.rst
Adding manifest input types `concentration(mass)` and `concentration(molar)`.
> Add concentration input types

- autoprotocol/container.py
- docs/changelog.rst
- test/container_test.py
well_from_shape was not returning correct wells for index beyond one.
For example, for a 384 well with origin well of A2 and shape of 96 well
to select, it should return the 2nd quadrant, however, the current code
returns the 1st quadrant wells. We added failing tests and fixed this bug
by using a new approach for calculating well indices and checking boundaries.
> Fix well_from_shape bug

- autoprotocol/builders.py
- test/liquid_handle_builder_test.py
This PR aims at enabling the passing of extra arguments in the `detection` dictionary within the `position_z` dict of the `LiquidHandleMethod` class.
Such extra arguments can be used to handle capacitive / pressure liquid level detection with liquid handlers that do not support the direct passing of thresholds in pascal or farads such as Hamilton STAR class liquid handlers.
The `LiquidHandle.builders.position_z` input checking method was rigidly sanitizing inputs to the expected arguments and stripping any extra arguments passed in the `detection` dict.
> Enable extra detection arguments in position_z dict

- autoprotocol/builders.py
- autoprotocol/liquid_handle/liquid_handle_method.py
- autoprotocol/liquid_handle/transfer.py
- autoprotocol/protocol.py
- test/liquid_handle_builder_test.py
- test/liquid_handle_integration_test.py
- test/liquid_handle_unit_test.py
The viscosity of liquid samples used in a laboratory ranges from very fluid (ie. acetone) to very thick (ie. glycerol). A limitation to the current `liquid_handle` instruction is that there is only an `air-displacement` mode to handle water-like liquid. While this is sufficient for liquids with relatively low viscosity, they should not be used for viscous samples due to the inability for air pressure to overcome the surface tension. 
To provide a more accurate way to handle these samples, the `positive-displacement` mode should be used for 'viscous' liquid class. Furthermore, there are devices that are capable of requesting liquid transfer amount in mass instead of volume. To allow such feature, optional density parameter is added to be able to convert mass to volume (and vice versa) as …
> Updating LiquidHandle instruction with 'density' parameter and 'positive_displacement' mode

- autoprotocol/protocol.py
- docs/changelog.rst
https://strateos.atlassian.net/jira/software/projects/STDEV/boards/58?selectedIssue=STDEV-35
User warnings are preventing protocol package from building and uploading to web. This is due to setting Protocol.propagate_properties to True, because it will use the .add_properties method instead of the .set_properties method. The .add_properties method purposefully uses user warnings when aliquot properties are overwritten. By changing to .set_properties, we can avoid building failures and copy the aliquot properties to the destination aliquot.
> Fixing propagate properties method

- autoprotocol/harness.py
- docs/changelog.rst
We currently default to instantiating a Protocol object in harness.run
However, that precludes the user from creating their own subclasses of
Protocol and using that in the harness.run method.
This would enable that use case, which would increase the flexibility
of the manifest/harness system.
> feat: support Protocol subclasses for harness.run

- docs/changelog.rst
We had some mislabelling with regards to bugs.
Under the auto-generated changelog, we should tag bugs with the `major`
tag if we're releasing it as part of a minor/major version bump
> docs: properly label changelog

- autoprotocol/protocol.py
- docs/changelog.rst
Modifications to the the method that Protocol.propagate_properties uses to propagate properties, solved internal Strateos issues when overwriting an aliquot property key. The main issue is the warning caused by overwriting keys is sent to stdout which prevents the building and and execution of the protocol on the Strateos Web app. However, the change breaks Ginkgo's expectation of how the properties are propagated. This PR reverts the method used back to the original `.add_properties` method. Since the original bug only is seen internally in a very specific edge case.
> Propagate aliquot properties bug

- docs/changelog.rst
- setup.py
As we're preparing for a major release, this is an opportunity to
upgrade some of our base dependencies.
This upgrades the base Pint version to 0.9 which brings some bugfixes
and better interop with other Python libraries.
See https://github.com/hgrecco/pint/blob/master/CHANGES#L259
Ideally we'll bump to 0.11, but there are some incompat issues which
we'll need to investigate.
> feat: Bump Pint to 0.9

- docs/changelog.rst
- docs/conf.py
- setup.py
As we're preparing for a major release, this is an opportunity to
upgrade some of our base dependencies.
This PR bumps our base Sphinx version to >=2.4, and also bumps our
other documentation related dependencies to their newest versions.
Notably, this brings in many bugfixes and some nicer UI elements such as
a nicer search bar.
The full changelog is available here:
https://www.sphinx-doc.org/en/master/changes.html#release-2-4-4-released-mar-05-2020
Verified that the docs build fine.
>  docs: Bump documentation dependencies

- autoprotocol/instruction.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
- docs/changelog.rst
- setup.py
As we're preparing for a major release, this is an opportunity to
upgrade some of our base dependencies.
This bumps our pytest dependency by one major version. Notably py35
support was dropped, and there has been multiple deprecations which we
are not affected by. There's also a bunch of bugfixes/improvements.
Pylint has been pinned to 2.5.2, which is the same as what we're running
in pre-commit.
Tox has been bumped to 3.15, which brings notable speedups.
>  build: Bump test dependencies

- .readthedocs.yml
- docs/changelog.rst
- docs/requirements.txt
We had a separate doc/requirements.txt file that was previously used for
maintaing documentation dependencies for readthedocs.org
Switching to the readthedocs config file would allow us to remove that
duplicated file and use the right build environment for generating docs.
> docs: Use readthedocs config file

- autoprotocol/builders.py
- test/liquid_handle_builder_test.py
fix: desired_mode
minimal_transfer in txappy returns None for `mode_params`. Updating ApPy to make it compatible.
> fix: compatibility with txappy

- autoprotocol/container_type.py
- docs/changelog.rst
- test/container_type_test.py
Summary:
Update humanize/robotize to support containers with up to 26*26 + 26 rows (A, B, C, …, Z, AA, AB….ZZ).
Refactored `humanize`, `robotize`, and `well_from_coordinates` to their own respective static functions.
Linked issue: https://strateos.atlassian.net/browse/OX-64
Test Plan:
Added unit test
> feat: add humanize and robotize support for 1536w

- autoprotocol/protocol.py
- docs/changelog.rst
- test/protocol_test.py
There are downstream libraries which call as_dict() for empty
refs/instructions. Since this is now a breaking change, choosing to
revert that change and slate it for 8.x.x
> revert: Protocol.as_dict() empty instructions/refs

- autoprotocol/version.py
- docs/changelog.rst
Changes from this release:
- [Bug] #261: Revert empty Protocol assertion check in as_dict()
> build: Release v7.1.1

- .pre-commit-config.yaml
- autoprotocol/builders.py
- autoprotocol/instruction.py
- autoprotocol/liquid_handle/transfer.py
- autoprotocol/protocol.py
- docs/changelog.rst
- test/instruction_test.py
- test/liquid_handle_integration_test.py
- test/protocol_test.py
Previously we were running black on `stable`, but this occasionally led
to local/CI discrepancies when the cache is utilized. Pinning it can
help reduce these issues.
> style: Pin black to 20.8b1

- autoprotocol/harness.py
- docs/changelog.rst
ASC-51 added formal support for concentration units (amount, mass,
volume) into the Autoprotocol spec.
This adds support for these units into the harness, keeping to a similar
namespace.
Note that support for `concentration(mass)`, `concentration(molar)`
should be deprecated in some future major version bump.
> feat: Add harness support for units specified in ASC-51

- .travis.yml
- docs/changelog.rst
We're currently spinning off multiple build jobs for all tests running
python 3.6.
We should only be spinning off a single deployment job, adding an
additional envvar filter for that.
> build: Fix Travis deployment issue

- autoprotocol/protocol.py
- docs/changelog.rst
avoid situations where 0 uL transfers result in an empty "groups" field in autoprotocol and therefore cause an error when submitted to web. This change will cause the error to occur upstream of a web submission, notifying the protocol writer to avoid generating acoustic transfer instructions with 0 volume
> acoustic transfer: raise an error if no transfers are generated

- autoprotocol/version.py
- docs/changelog.rst
Changes from this release:
- [Feature] #271: Add 96-ubottom-clear-tc container type
- [Bug] #270: 0 uL acoustic transfer raises an error instead of creating empty ‘groups’ field
- [Support] #269: Update travis.yml to trigger deployment only once
> build: Release v7.3.0

- autoprotocol/version.py
- docs/changelog.rst
Included in this release:
* :feature: #276 Add 96-flat-white-dc container type
* :bug: #275  Fix acoustic transfer `one_source` bug to take dead volume into account.
* :bug: #274  Container.wells_with(prop, val) not returning wells with val due to `is` operator instead of `==`
> build: Release v7.4.0

- .travis.yml
- docs/changelog.rst
Travis uses bash syntax for conditionals instead of its usual expressions syntax. See https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
Tested this on a test repository.
> build: Fix Travis bash syntax

- autoprotocol/builders.py
- docs/changelog.rst
- test/builder_test.py
The FlowCytometry excitation field should be optional and support
concurrent specification of multiple lasers.
Prior to this fix, this breaks if a gating channel (e.g. SSC) is
specified along side another non-gating channel.
Note this is a breaking change, as the ordering of the builder function
is changed.
> fix: FlowCytometry laser builder bug

- .pre-commit-config.yaml
- autoprotocol/version.py
- docs/changelog.rst
* :bug: `277` Fix travis.yml deployment syntax
* :bug:`270 major` 0 uL acoustic transfer raises an error instead of creating empty 'groups' field
> Build: Release v7.4.1

- .github/workflows/ci.yml
- docs/changelog.rst
- tox.ini
There are no obvious regressions for Python 3.9. Checking this in to our
test suite so that we can be notified of any future regressions.
> feat: Support Python 3.9

- docs/changelog.rst
- setup.py
Our current pypi page has no long_description,
see https://pypi.org/project/autoprotocol/
Let's use our current README to populate that field.
> support: Add long description

- .github/workflows/ci.yml
- docs/changelog.rst
The migration to GitHub actions did not include the previous CodeCov
functionality. This adds it in.
> build: Add CodeCov action

- .isort.cfg
- .pre-commit-config.yaml
- autoprotocol/builders.py
- autoprotocol/constants.py
- autoprotocol/container.py
- autoprotocol/container_type.py
- autoprotocol/harness.py
- autoprotocol/liquid_handle/liquid_handle_method.py
- autoprotocol/liquid_handle/mix.py
- autoprotocol/liquid_handle/transfer.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- test/builder_test.py
- test/conftest.py
- test/container_test.py
- test/cover_test.py
- test/exception_test.py
- test/instruction_test.py
- test/liquid_handle_builder_test.py
- test/liquid_handle_integration_test.py
- test/liquid_handle_unit_test.py
- test/manifest_test.py
- test/protocol_test.py
- test/provision_test.py
- test/unit_test.py
- test/util_test.py
- test/well_test.py
Adds an isort dependency for automatic import sorting. This is purely a
non-functional quality-of-life change.
> style: Automatically sort imports

- autoprotocol/informatics.py
- autoprotocol/instruction.py
- autoprotocol/protocol.py
- docs/changelog.rst
- test/informatics_test.py
- test/instruction_test.py
- test/protocol_test.py
Add new optional attribute `informatics`
* `informatics` defaults to None for backward compatibility
* `informatics` is serialized only when it is not empty
* update `provision` to include `informatics` as an optional param
> feat: Add informatics attribute to Instruction

- AUTHORS.rst
- LICENSE.rst
- autoprotocol/builders.py
- autoprotocol/constants.py
- autoprotocol/container.py
- autoprotocol/container_type.py
- autoprotocol/harness.py
- autoprotocol/informatics.py
- autoprotocol/instruction.py
- autoprotocol/liquid_handle/liquid_class.py
- autoprotocol/liquid_handle/liquid_handle_method.py
- autoprotocol/liquid_handle/mix.py
- autoprotocol/liquid_handle/tip_type.py
- autoprotocol/liquid_handle/transfer.py
- autoprotocol/protocol.py
- autoprotocol/unit.py
- autoprotocol/util.py
- docs/changelog.rst
Update copyright year to 2021 and active authors list
> support: Update copyright year and active authors

- autoprotocol/instruction.py
- autoprotocol/protocol.py
- docs/changelog.rst
- test/protocol_test.py
@yangchoo 
Informatics need to be implemented in LH as well.
However, there's one issue... 
In LH, transfer form one source to multiple destinations (e.g. source=resourceA, dests = [aliquot1, aliquot2 aliquot3]) would instantiate 3 Instruction: Instruction("liquid_handle" for resourceA to aliquot1), Instruction("liquid_handle" for resourceA to aliquot2), Instruction("liquid_handle" for resourceA to aliquot3). This is a problem with how we are handling informatics, since informatics is provided at Protocol level (p.transfer), but the validations are happening at each Instruction... which means if Informatics has dest wells: [aliquot1, aliquot2, aliquot3], it fails (on informatics wells is part of Instruction wells) since at Instruction, there is one destination well at a time.
We could …
> feat: add informatics to LH

- autoprotocol/instruction.py
- docs/changelog.rst
- test/protocol_test.py
AttachCompounds serializes wells into Well or list(Well). It should always be list(Well)
> fix: bug on info wells should be a list

- autoprotocol/version.py
- docs/changelog.rst
preparing for release-v7.9.4
* :release:`7.9.4 <2021-09-21>`
* :feature:`308` Update `liquid_handle_dispense` instruction to allow for multiple intake hoses in source
> verion bump and changelog update

- autoprotocol/harness.py
- docs/changelog.rst
- test/manifest_test.py
Extracting mass from containers was using the key `mass_mg` when we actually expect `mass` attribute (no underscore unit). This PR fixes that. Updated test.
> Fix container mass extraction

- autoprotocol/container.py
- autoprotocol/harness.py
- test/manifest_test.py
When we receive a JSON payload with the expected schema for compound declaration, we should associate these linked compounds to the `Well` they reside in.
This is the kind of structure we're expecting to receive, and we should only allow compounds with `id`, `molecularWeight`, and `smiles` keys to be associated, as we may need some of these keys in downstream applications. Any other keys to be considered should be included in a new ASC (autoprotocol standard change)
```
"compounds": [
{.
"id": "123",
"molecularWeight": 100,
"smiles": "CCCC",
}
]
```
> Extract list of compounds, and associated metadata, when constructing aliquots with said data

- autoprotocol/container.py
- docs/changelog.rst
- test/manifest_test.py
Compounds should be set to an aliquot (Well) even if all information is not present.  This change introduces more flexibility to set parameters associated with compounds to a given Well.
> Update `set_compounds` on Well to allow compounds without all properties

- autoprotocol/container.py
- setup.py
- test/container_test.py
When Well.set_volume() exceeds maximum allowed, the error message returned should include Container name, ID (if available) and the Well index number.
** STDV Internal Only **
(The comment below may be removed before merge to origin repo due to the internal STDV-only info)
Ticket: https://strateos.atlassian.net/browse/STDV-823
Test: tox script validation.
> Enhanced error message(s) when Well.set_volume() exceeds maximum allowed

- autoprotocol/version.py
- docs/changelog.rst
Reverts autoprotocol/autoprotocol-python#361
Not building and publishing due to 
```
UserWarning: The version specified ('"""Maintains current version of package"""\n__version__ = "8.0.0"\n') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
"details." % version
> Revert "release version 8.0.0"

- .pre-commit-config.yaml
CI pipeline not passing due to known issue https://github.com/tox-dev/tox/pull/2908. The latest poetry version is colliding with version of isort. The pre-commit-hook installs both making the lint CI step fail.
> fix(pre-commit-hook): isort incompatiability with latest poetry version

- autoprotocol/version.py
- docs/changelog.rst
Update changelog and prepare for new release of Autoprotocol-python version 10.1.0
> Release Appy v10.1.0

- autoprotocol/version.py
- docs/changelog.rst
Adjusted `96-deep-kf` and `96-v-kf` container types `true_max_vol` to 1.8mL and added validations in `MagBuilders` class such that plates being put onto KF device do not exceed working vol with comb
> SCIENG-186: Release APpy with new `96-deep-kf` params

- autoprotocol/builders.py
- autoprotocol/protocol.py
- autoprotocol/types/builders.py
- autoprotocol/types/protocol.py
- autoprotocol/unit.py
- autoprotocol/version.py
- docs/changelog.rst
- test/builder_test.py
Continuing updates for dataclasses and further typing...
> chore: make updates to align with autoprotocol-service

- autoprotocol/liquid_handle/transfer.py
- autoprotocol/version.py
- docs/changelog.rst
Identified an error scheduling runs that contained liquid transfer instructions. This reverts a recently introduced method.
Previous behavior called `_rec_tip_type` from the parent class of `Transfer` but didn't assign it to self.tip_type
Scheduled a run and confirmed this fixes the error.
> Revert rec tip type assignment

- autoprotocol/builders.py
- autoprotocol/protocol.py
- autoprotocol/util.py
- autoprotocol/version.py
- docs/changelog.rst
- test/liquid_handle_dispense_test.py
- test/util_test.py
[SCIENG-223](https://strateos.atlassian.net/browse/SCIENG-223)
Started new branch, but from `master`
[SCIENG-223]: https://strateos.atlassian.net/browse/SCIENG-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
referencing [#1109](https://github.com/strateos/internal_protocols/pull/1109)
Release `txappy` and then:
Testing Mantis Driver Task will cover following tests
> SCIENG-223: Update dependencies to allow for mantis liquid handle dispense
