autoprotocol/harness.py
test/manifest_test.py

Make 'group' type inputs default to the defaults of their inputs

---

autoprotocol/instruction.py
autoprotocol/protocol.py

remove unsupported reagent references

---

autoprotocol/container.py
autoprotocol/container_type.py
autoprotocol/harness.py
autoprotocol/protocol.py
autoprotocol/unit.py
test/container_test.py
test/protocol_test.py
test/unit_test.py

Fixed all unit tests that were failing under Python 3.4.2

More python3 compatibility

---

.gitignore
autoprotocol/unit.py

cleaned up unit classes methods, numerous instances where already existing _check_type could have been used but wasn't.

Unit refactor

---

autoprotocol/container.py

@therzka allowing lists of wells to be submitted according to spec (or just change description)

fix list of list issue in wells

---

CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
docs/autoprotocol.rst
test/protocol_test.py

@therzka , @cojofra This is minimal and only mentions `mode="top"`.  Feel free to commandeer this branch or scrap the pull request entirely if you had other plans.

Add image_plate instruction.

---

autoprotocol/protocol.py

Small change to simplify logic in Protocol constructor.

Make instruction instantiation more concise

---

CHANGELOG.md
autoprotocol/protocol.py
autoprotocol/unit.py

Volume tracking when using dispense(), Unit object representation

---

autoprotocol/container.py
autoprotocol/harness.py

add aliquot name return to protocol info

---

autoprotocol/harness.py

check if name exists before assignment

---

.coveragerc
autoprotocol/container.py
autoprotocol/util.py
test/container_test.py
tox.ini

Also fixes a couple of minor test and documentation bugs and improves type consistency from some functions (Container.quadrant, Container.inner_wells).
This is my first PR against this project so please let me know if I've missed any style conventions, etc!

Bring container.py test coverage to 100%

---

autoprotocol/container_type.py
test/container_type_test.py
test/exception_test.py

Identified some off-by-one bounds-checking bugs.

Improve coverage of container_type.py

---

CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
test/protocol_test.py

This PR adds support for the `measure_concentration` operation.

Feature measure_concentration

---

CHANGELOG.md
autoprotocol/container.py
autoprotocol/container_type.py
test/container_test.py
test/container_type_test.py

Allowing humanize and robotize functions in ContainerType/Container to take in lists will be helpful for converting well maps. This is something that was ran into in the process of developing an analysis function in the Transcriptic library.

Extend Humanize and Robotize

---

autoprotocol/container.py
autoprotocol/harness.py
autoprotocol/instruction.py
autoprotocol/pipette_tools.py
autoprotocol/protocol.py
autoprotocol/util.py
docs/conf.py
setup.py
test/container_test.py
test/manifest_test.py
test/protocol_test.py
tox.ini

Fixed all flake8 warnings/errors.

Fix all flake8 errors

---

autoprotocol/harness.py

The harness didn't support gradient input, meaning that the new gradient support in the UI failed during autoprotocol generation. I also cleaned up the thermocycle input error message to take advantage of multi-line string. I'm open to feedback on the formatting/content of the error message.

Add thermocycle gradient step support to harness

---

autoprotocol/harness.py
autoprotocol/unit.py

A little more robust error handling.

Improve exception handling for Unit and Unit uses

---

CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
test/protocol_test.py

ASC: Add cycles parameter to illumina_sequence

Illumina seq params

---

CHANGELOG.md
autoprotocol/protocol.py
test/protocol_test.py

Summary:
Add time constraints top-level field in accordance with the time constraints ASC
https://docs.google.com/document/d/1pbI6OgWu8TV7P6jr9klrR-WwN7qowgWNBSq9KQ7jheo/edit
Fixes T6227
Test Plan: passes tox
Reviewers: yangchoo, Vanessa
Maniphest Tasks: T6227
Differential Revision: https://work.r23s.net/D4951
Improvements include:
- Add mirroring option
- Add checks for impossible constraints
- Add checks for <0 index instructions

Add time constraints

---

CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
test/protocol_test.py

Dispense - Add resource_id as replacement for reagent added

Resource id dispense

---

CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
test/cover_test.py
test/protocol_test.py

- enable automatic cover before incubate
- _add_cover and related functions do not act on tubes
- assert container for incubate refs and adjust tests
- add assertions and tests for flow_analyze
-  fix spin automatic cover and adjust tests
- spin cover documentation

autocover and flow_analyze improvements

---

CHANGELOG.md
autoprotocol/protocol.py
docs/protocol.rst

Linting and documentation improvements

minor fixes to time_constraint docs

---

.gitignore
CHANGELOG.md
autoprotocol/instruction.py
autoprotocol/protocol.py
setup.py
test/protocol_test.py

Adding support for `blue_wash` instruction and supporting test

Adding support for `blue_wash`

---

autoprotocol/protocol.py
docs/changelog.rst
test/protocol_test.py

Use UnitError and update order of parameter validation.

Bug fix in flow analyze

---

autoprotocol/harness.py
docs/autoprotocol.rst
docs/changelog.rst

Summary: surface seal on store func
Test Plan: tox
Reviewers: Kadhir
Differential Revision: https://work.r23s.net/D5548

update documentation for seal_on_store

---

autoprotocol/container.py
docs/changelog.rst
docs/container.rst
test/container_test.py

Adding small helper method to Container class to improve readability of Autoprotocol-Python

Add tube method

---

autoprotocol/container_type.py
docs/AUTHORS.rst
docs/changelog.rst
docs/container_type.rst
docs/setup.py
setup.py

New plate type 96-flat-clear-clear-tc and increment version for release

add 96-flat-clear-clear-tc to container types

---

autoprotocol/container.py
docs/changelog.rst
docs/setup.py
setup.py
test/container_test.py

Makes set_properties act as expected.

Change set_properties so that it completely overwrites the existing properties dictionary

---

docs/changelog.rst
docs/requirements.txt

We need to update the docs/requirements.txt in order for ReadTheDocs to build properly

Update docs/requirements for RTD

---

autoprotocol/builders.py
autoprotocol/instruction.py
autoprotocol/protocol.py
docs/changelog.rst

This PR adds a new flow cytometry instruction and related protocol method.

Add FlowCytometry instruction/protocol methods

---

autoprotocol/instruction.py
autoprotocol/protocol.py
docs/changelog.rst

This PR updates the docstrings for the Incubate instruction and related protocol method

update Incubate instruction/protocol co2 parameter docstrings

---

autoprotocol/protocol.py
docs/changelog.rst

accurately pass through store_lid in p.uncover

actually store the lid in uncover method

---

autoprotocol/builders.py
docs/changelog.rst
test/builder_test.py

This PR implements ASC-041 (https://github.com/autoprotocol/ascs/pull/3), adding `read_position` and `position_z` to the Spectrophotometry instruction

Implement ASC-041

---

autoprotocol/version.py
docs/changelog.rst

Bump version to release new features

Bump version to 5.2.0

---

autoprotocol/container.py
docs/changelog.rst
test/container_test.py

Implement equality for well groups.

Wellgroup equality

---

autoprotocol/container_type.py
autoprotocol/util.py
autoprotocol/version.py
docs/changelog.rst

Fix an issue with python2 division that led to incorrect numbers of wells having their volume changed during liquid_handle transfers.

Fix util division in python2

---

.arcconfig
docs/changelog.rst

Remove phabricator URI from .arcconfig

Remove phabricator URI

---

autoprotocol/version.py
docs/changelog.rst

Bump to 5.3.0

---

autoprotocol/version.py
docs/changelog.rst

Bump to 5.4.0

---

autoprotocol/harness.py
docs/AUTHORS.rst
docs/changelog.rst
test/manifest_test.py

Functionality to provide manifest preview in interactive python mode

New harness function for easily getting preview parsed from manifest

---

autoprotocol/harness.py
autoprotocol/instruction.py
docs/changelog.rst

Adds `warm_35` as an incubation location

Add warm35

---

autoprotocol/version.py
docs/changelog.rst

Update the changelog and bump the version.

Bump version to 6.1.1

---

autoprotocol/builders.py
docs/changelog.rst

fixing docstring preventing build

Builder docstring change

---

README.rst

Adding Dev Env section in README.rst

feat: upadate README with Dev Env setup

---

.travis.yml
docs/changelog.rst

Add travis steps for uploading to releases and pypi upon pushing tag

 build: add CD step to travis.yml

---

autoprotocol/version.py
docs/changelog.rst

We are ready for release. Bumping to 6.2.0 to prepare for it

build: bump version to 6.2.0 for release

---

.travis.yml
README.rst
autoprotocol/builders.py
autoprotocol/container.py
autoprotocol/container_type.py
autoprotocol/harness.py
autoprotocol/instruction.py
autoprotocol/liquid_handle/liquid_class.py
autoprotocol/liquid_handle/liquid_handle_method.py
autoprotocol/liquid_handle/mix.py
autoprotocol/liquid_handle/tip_type.py
autoprotocol/protocol.py
autoprotocol/unit.py
autoprotocol/util.py
docs/changelog.rst
setup.py
test/protocol_test.py
tox.ini

Upgrade base Python version to Python 3.6

build: Upgrade to Python 36

---

autoprotocol/container_type.py
docs/changelog.rst

Adding two capabilities to this new plate type

feat: add `absorbance` and `fluorescence` capabilities to 96-well-v-bottom container type

---

docs/changelog.rst
test/protocol_test.py

Adding test for expected propagate property behavior when the destination well has prior properties.

Add expected propagate_properties behavior tests

---

autoprotocol/version.py
docs/changelog.rst

Changes from this release:
- [Feature] #254: Add support for provisioning of resources by mass
- [Feature] #258: Add time_constraints value to the Protocol attributes
- [Feature] #259: Add humanize and robotize support for 1536w

build: Release v7.1.0

---

autoprotocol/version.py
docs/changelog.rst

Changes from this release:
- [Feature] #265: Add support for mass_concentration, amount_concentration and volume_concentration, as specified in ASC-51
- [Support] #267: Pin black version to reduce CI/local inconsistencies. Pin to 20.8b1

build: Release v7.2.0

---

.pre-commit-config.yaml
autoprotocol/container.py
docs/changelog.rst

STDV-333: https://strateos.atlassian.net/browse/STDV-333

Stdv 333 container with wells bug

---

.pre-commit-config.yaml
autoprotocol/protocol.py
docs/changelog.rst
test/protocol_test.py

well.volume -> well.available_volume to account for dead volume
branch should be STDV-304 not 340... oops

STDV 304 acoustic transfer one_source bug fix

---

README.rst
docs/changelog.rst
setup.py

Add downloads badge so that we can keep track of usage rate of this
package.

build: Add Downloads Badge

---

autoprotocol/version.py
docs/changelog.rst

#288 Add "Compound" to derived types
#283 Support Python 3.9
#284 add isort for automatic import sorting
#286 CodeCov action for GitHub actions
#285 use readme.rst for long description
#282 migrate CI from travis to GitHub actions
#281 Add downloads badge to track package usage

build: Release v7.5.0

---

autoprotocol/version.py
docs/changelog.rst

#292 Add Informatics to p.transfer
#290 Add informatics attribute to Instruction
#291 Update copyright year and authors

build: Release v7.6.0

---

autoprotocol/version.py
docs/changelog.rst

#294 Instruction returns AttachCompound `wells` in a list of Well

build: Release v7.6.1

---

autoprotocol/container_type.py
docs/changelog.rst

STDV-563: https://strateos.atlassian.net/browse/STDV-563

STDV-563: falcon96 ubottom remove low evap cover

---

autoprotocol/compound.py
autoprotocol/harness.py
autoprotocol/protocol.py
docs/changelog.rst
test/informatics_test.py
test/instruction_test.py
test/manifest_test.py
test/protocol_test.py

* Change Compound to take in SMILES instead of InChI

feat: add SMILES to Compound

---

autoprotocol/version.py
docs/changelog.rst

#297 Add SMILES to Compound
#296 Remove low-evaporation cover type from FALCON96UBOTTOM

build: Release v7.7.0

---

autoprotocol/container.py
autoprotocol/harness.py
test/manifest_test.py

Update harness to extract mass from `refs`.

PP-3914: extract container mass

---

autoprotocol/container_type.py
autoprotocol/version.py
docs/changelog.rst

https://strateos.atlassian.net/browse/PP-3963

remove standard cover type from 96-ubottom-clear-tc

---

docs/changelog.rst

release: v7.9.5

---

.github/workflows/ci.yml
docs/changelog.rst
setup.py
tox.ini

Add Python 3.10 to the test suite as there are no obvious regressions.

feat: Support Python 3.10

---

autoprotocol/version.py
docs/changelog.rst

Description:
* :release:`7.11.0 <2021-11-07>`
* :feature:`327` Update container class to have contextual custom properties

release-v7.11.0

---

autoprotocol/protocol.py
docs/changelog.rst
test/protocol_test.py

Adding new valid step_size for Dispense Instruction

Update Dispense allowed step_size

---

autoprotocol/version.py
docs/changelog.rst

Included in this release:
* :release:`7.12.0 <2021-11-11>`
* :feature:`330` Update allowed step_size in `Dispense`

release 7.12.0

---

autoprotocol/container.py
autoprotocol/protocol.py

Related to https://github.com/strateos/autoprotocol-service/pull/45/files

update: cast Well index as int to allow APService AliquotRef usage

---

autoprotocol/version.py
docs/changelog.rst

This is a minor bump, as the changes are backwards compatible, but introduce a new feature

prepare for release v7.13.0

---

autoprotocol/container.py
docs/changelog.rst
test/manifest_test.py

Add concentration & solubility_flag in aliquot compounds.
[Corresponding Web PR](https://github.com/strateos/web/pull/2236)

feat: add concentration & solubility flag in well (aliquot) compounds

---

autoprotocol/version.py
docs/changelog.rst

This is a minor bump, as the changes are backwards compatible, but introduce a new feature

release-v7.13.1

---

autoprotocol/version.py
docs/changelog.rst

Feature:`337` Update requirements for tracking concentration on compounds, set defaults to None

Release 7.14.0

---

autoprotocol/version.py
docs/changelog.rst

New container type Corning 4513 384 well round bottom low volume plate with nonbinding surface coating

Release Autoprotocol 7.14.2

---

autoprotocol/version.py
docs/changelog.rst

releasing ctx_properties changes/updates

Release 7.14.4

---

autoprotocol/container_type.py
docs/changelog.rst

Added `384-spl-uv-max`container type and updated changelog doc

SCIENG-58: Added `384-spl-uv-max` container type

---

autoprotocol/version.py
docs/changelog.rst

Update changelog to include v7.15.1

Release package version 7.15.1

---

autoprotocol/version.py

release-v801

---

autoprotocol/version.py
docs/changelog.rst

fix: release hotfix verion bump v9.1.1
